FROM postgres:14-alpine
ENV ALPINE_MIRROR "http://dl-cdn.alpinelinux.org/alpine"
WORKDIR /usr/src/db
COPY ["./data.gz", "./"]
EXPOSE 5432
RUN chown postgres:postgres /run/postgresql/
RUN cd
RUN chmod 0700 /var/lib/postgresql/data
RUN su -c 'initdb -D /var/lib/postgresql/data' postgres
RUN echo "host all all 0.0.0.0/0 md5" >> /var/lib/postgresql/data/pg_hba.conf
RUN echo "listen_addresses='*'" >> /var/lib/postgresql/data/postgresql.conf
RUN su -c "pg_ctl start -D /var/lib/postgresql/data" postgres; \
  su postgres -; sleep 3; \
  psql -U postgres < example.sql; \
  su -c "pg_ctl stop -D /var/lib/postgresql/data" postgres
CMD ["/bin/sh"]